#pragma once
#include <nds.h>

static const int TEX_SIZE = 8;

extern const u16 TEX_GRASS_TOP[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_DIRT[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_STONE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_WOOD_TOP[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_WOOD_SIDE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_LEAVES[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_SAND[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_WATER[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_COBBLE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_PLANKS[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_BRICK[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_GLASS[TEX_SIZE * TEX_SIZE];

extern const u16 TEX_BIRCH_WOOD_TOP[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_BIRCH_WOOD_SIDE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_SPRUCE_WOOD_TOP[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_SPRUCE_WOOD_SIDE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_JUNGLE_WOOD_TOP[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_JUNGLE_WOOD_SIDE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_BIRCH_LEAVES[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_SPRUCE_LEAVES[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_JUNGLE_LEAVES[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_BIRCH_PLANKS[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_SPRUCE_PLANKS[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_JUNGLE_PLANKS[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_SANDSTONE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_OBSIDIAN[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_GRAVEL[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_BOOKSHELF[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_WHITE_WOOL[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_GOLD_BLOCK[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_IRON_BLOCK[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_TORCH[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_CRAFTING_TABLE_TOP[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_CRAFTING_TABLE_SIDE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_CRAFTING_TABLE_FRONT[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_FURNACE_TOP[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_FURNACE_SIDE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_FURNACE_FRONT[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_COAL_ORE[TEX_SIZE * TEX_SIZE];

extern const u16 TEX_ITEM_APPLE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_ITEM_STICK[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_ITEM_COAL[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_ITEM_WOOD_PICKAXE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_ITEM_STONE_PICKAXE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_ITEM_WOOD_AXE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_ITEM_STONE_AXE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_ITEM_WOOD_SHOVEL[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_ITEM_STONE_SHOVEL[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_ITEM_WOOD_SWORD[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_ITEM_STONE_SWORD[TEX_SIZE * TEX_SIZE];
