#pragma once
#include <nds.h>

static const int TEX_SIZE = 8;

extern const u16 TEX_GRASS_TOP[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_DIRT[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_STONE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_WOOD_TOP[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_WOOD_SIDE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_LEAVES[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_SAND[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_WATER[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_COBBLE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_PLANKS[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_BRICK[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_GLASS[TEX_SIZE * TEX_SIZE];

extern const u16 TEX_BIRCH_WOOD_TOP[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_BIRCH_WOOD_SIDE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_SPRUCE_WOOD_TOP[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_SPRUCE_WOOD_SIDE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_JUNGLE_WOOD_TOP[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_JUNGLE_WOOD_SIDE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_BIRCH_LEAVES[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_SPRUCE_LEAVES[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_JUNGLE_LEAVES[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_BIRCH_PLANKS[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_SPRUCE_PLANKS[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_JUNGLE_PLANKS[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_SANDSTONE[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_OBSIDIAN[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_GRAVEL[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_BOOKSHELF[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_WHITE_WOOL[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_GOLD_BLOCK[TEX_SIZE * TEX_SIZE];
extern const u16 TEX_IRON_BLOCK[TEX_SIZE * TEX_SIZE];
